title: Container of Unique Elements
description: A library for managing unique elements in a container.
theme: jekyll-theme-minimal
url: "https://Huanhuan-Jiang.github.io" # Your GitHub username
baseurl: "/containerofuniqueelements" # Your repository name