#!/bin/bash

# Find all Markdown files and update their last_modified_at field
for file in $(git ls-files '*.md'); do
  # Get the last commit date for the file
  last_modified=$(git log -1 --format="%ci" "$file")
  
  # Update the `last_modified_at` field in the front matter
  sed -i.bak -E "s/(last_modified_at: ).*/\1\"${last_modified}\"/" "$file"
  
  # Remove backup file generated by sed (macOS specific)
  rm -f "${file}.bak"
done
